name: Build and deploy Node.js app to Azure Web App - naiveoj

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      # Optional: run tests before deployment
      - name: Run tests
        run: npm test --if-present

      # Prune dev dependencies to match production environment
      - name: Prune dev dependencies
        run: npm prune --production

      # Prepare deployment package
      - name: Prepare artifact
        run: |
          mkdir deploy
          cp -R .next package.json node_modules public deploy/
          # Optional: include env file if needed
          if [ -f .env.production ]; then cp .env.production deploy/; fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9A6A1D46E32B4153AD3AC11DA9A4060E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_151ADCDBF5904BAAB65A8B43B380AF97 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9107F3F31E1F4B6BA58A60E2643AE5A7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "naiveoj"
          slot-name: "Production"
          package: deploy
